;
; File generated by cc65 v 2.18 - Git b5f0c04
;
	.fopt		compiler,"cc65 v 2.18 - Git b5f0c04"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_acia_puts
	.import		_acia_put_newline
	.import		_timer_setup
	.import		_IRQ_enable
	.export		_print_f
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$41,$68,$6F,$6A,$20,$7A,$64,$65,$20,$69,$6E,$74,$65,$72,$72,$75
	.byte	$6F,$74,$00

; ---------------------------------------------------------------
; void __near__ print_f (char *s)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_f: near

.segment	"CODE"

	jsr     pushax
	jsr     _acia_put_newline
	jsr     ldax0sp
	jsr     _acia_puts
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     push0
	jsr     _IRQ_enable
	jsr     _timer_setup
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _print_f
L0002:	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	bra     L0002

.endproc

